services:
    postgresql:
        image: postgres:18.0
        user: postgres
        restart: always
        container_name: 'pgsql-dbc-dev'
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: dbc_local # keep same as setup-dev.sql
            TZ: Asia/Shanghai
        ports:
            - '5433:5432'
        volumes:
            - 'pgsql-dbc-dev:/var/lib/postgresql/data'
            - './database/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql'

volumes:
    pgsql-dbc-dev:
