services:
    postgresql:
        image: postgres:18.0
        user: postgres
        restart: always
        container_name: 'pgsql-dbc-dev'
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: dbc_local # keep same as setup-dev.sql
            TZ: Asia/Shanghai
        ports:
            - '5433:5432'
        volumes:
            - 'pgsql-dbc-dev:/var/lib/postgresql/data'
            - './database/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql'

    redis:
        image: redis:7.4.7
        restart: always
        container_name: 'redis-dbc-dev'
        environment:
            TZ: Asia/Shanghai
        command: redis-server --requirepass redis.local.123
        ports:
            - '6379:6379'
        volumes:
            - 'redis-dbc-dev:/data'

    redisinsight:
        image: redislabs/redisinsight:latest
        restart: always
        container_name: 'redisinsight-dbc-dev'
        environment:
            TZ: Asia/Shanghai
        ports:
            - '5540:5540'
        volumes:
            - 'redisinsight-dbc-dev:/data'
        depends_on:
            - redis

volumes:
    pgsql-dbc-dev:
    redis-dbc-dev:
    redisinsight-dbc-dev:
