miniprogram:
    server:
        port: MINIPROGRAM_SERVER_PORT
    datasource:
        host: MINIPROGRAM_DB_HOST
        port: MINIPROGRAM_DB_PORT
        database: MINIPROGRAM_DB_NAME
        schema: MINIPROGRAM_DB_SCHEMA
        username: MINIPROGRAM_DB_USER
        password: MINIPROGRAM_DB_PASSWORD

console:
    server:
        port: CONSOLE_SERVER_PORT
    datasource:
        host: CONSOLE_DB_HOST
        port: CONSOLE_DB_PORT
        database: CONSOLE_DB_NAME
        schema: CONSOLE_DB_SCHEMA
        username: CONSOLE_DB_USER
        password: CONSOLE_DB_PASSWORD
