miniprogram:
    server:
        port: 3000
    cors:
        origin: '*'
        credentials: true
    datasource:
        host: replace_me
        port: replace_me
        database: replace_me
        schema: replace_me
        username: replace_me
        password: replace_me
    logger:
        level: warn
        prettyPrint: false
    cache:
        host: replace_me
        port: replace_me
        username: replace_me
        password: replace_me
        ttl: 1800000

console:
    server:
        port: 4000
    cors:
        origin: '*'
        credentials: true
    datasource:
        host: replace_me
        port: replace_me
        database: replace_me
        schema: replace_me
        username: replace_me
        password: replace_me
    logger:
        level: warn
        prettyPrint: false
    cache:
        host: replace_me
        port: replace_me
        username: replace_me
        password: replace_me
        ttl: 1800000
