miniapp:
    server:
        port: 3000
    datasource:
        host: replace_me
        port: replace_me
        database: replace_me
        schema: replace_me
        username: replace_me
        password: replace_me
    logger:
        level: warn
        prettyPrint: false

console:
    server:
        port: 4000
    datasource:
        host: replace_me
        port: replace_me
        database: replace_me
        schema: replace_me
        username: replace_me
        password: replace_me
    logger:
        level: warn
        prettyPrint: false
