miniapp:
    server:
        port: 9000
    datasource:
        host: dot_put_secret_here
        port: dot_put_secret_here
        database: dot_put_secret_here
        schema: dot_put_secret_here
        username: dot_put_secret_here
        password: dot_put_secret_here
    logger:
        level: warn
        prettyPrint: false

console:
    server:
        port: 9000
    datasource:
        host: dot_put_secret_here
        port: dot_put_secret_here
        database: dot_put_secret_here
        schema: dot_put_secret_here
        username: dot_put_secret_here
        password: dot_put_secret_here
    logger:
        level: warn
        prettyPrint: false
