miniprogram:
    server:
        port: 3000
    cors:
        origin: '*'
        credentials: true
    datasource:
        host: localhost
        port: 5433
        database: dbc_local
        schema: dbc
        username: dbc_miniprogram_writer
        password: dbc.local.123
    logger:
        level: debug
        prettyPrint: true
    cache:
        host: localhost
        port: 6379
        username: default
        password: redis.local.123
        ttl: 1800000

console:
    server:
        port: 4000
    cors:
        origin: '*'
        credentials: true
    datasource:
        host: localhost
        port: 5433
        database: dbc_local
        schema: dbc
        username: dbc_console_writer
        password: dbc.local.123
    logger:
        level: debug
        prettyPrint: true
    cache:
        host: localhost
        port: 6379
        username: default
        password: redis.local.123
        ttl: 1800000
